install:
  - ps: iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
  - choco upgrade chocolatey
  - choco install rust-ms
  - refreshenv
  - cargo -V

build: none

test_script:
  - cargo build --release
  - cargo test --verbose

