language: rust
rust:
- stable
- beta
- nightly
os:
- linux
- osx
matrix:
  allow_failures:
  - rust: nightly
deploy:
  provider: releases
  api_key:
    secure: AGOWGYVWUaHDlQGVypYevU5r1A87eEifGg9SxF8wdDR/MWY/l2Uvmen4gbBQF9aPZm4gEYPvV/SQ+XeIC5ME0QjKWtRbBNuOJQGvRZ7dhWd8FoBLHRX0N9y87axeCjFMMEngkyg1B3B3kpDeXzY0UT/ClUBTNTuYeVdcWuTEjyUCI81WAkCSVrnkuQVNkQVXZi20tuIG5ZtnkxxWYZWOJ01al2vjW9K2qtjqXs3D0u6sdmuMkt6quZ3FE9cTdS3KDARO1PVVANZTsXLx3CQa55SbDj53xYNxk1FnqIP2L43zrE7s5J8ROdNGyCVRgqXiKKZ1znIpEf8s4FxtoWEgOzFPj8aLClHMdhM27kxvKFC0N3TPnOxI+1HNkuOxXz3nW7EjnEc45MaXyDDuZhSKJ892sTJLXaTXPC45LN5B4gMYHVFno9ceWZpLTbpJ23AA1xNBg1VLNx6Pu5LoYfOqH2qhgqEAlntYHOwOoXJX/6xraOF4gbDLQ33G+aTipufDAzV1Zixrc7ZQzZHPAeMs2vxJ2ZPFNe4FPztcKsyEFKPIpPZJPKsjTVt6Up0/ay3LwUCxkv+MyY10pFsJhxonO1NUnueAtPQ/9wV5v5XJXGaC7Dkw10iaEIEtYJFLgCpay72V2VwbwOXdeFkKfbgkqvOtR5bIrcnT/O6LebW6RUM=
  file: 'target/release/xxd-rs'
  on:
    repo: Nicoretti/xxd-rs
    branch: master
    tags: true
