language: rust
rust:
- stable
os:
- linux
- osx
script:
- cargo test
- cargo build --release
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 'target/release/xxd-rs'
  on:
    repo: Nicoretti/xxd-rs
    branch: master
    tags: true
